title: The pages tittle
description: learning about Jekyll docs
theme: just-the-docs

logo: "/assets/images/logo.png"

url: https://ChenPeleg.github.io/documentation-pages

color_scheme: darker

aux_links:
  View on GitHub: https://github.com/ChenPeleg/documentation-pages
