title: The pages tittle
description: learning about Jekyll docs
theme: just-the-docs


url: https://ChenPeleg.github.io/documentation-pages

aux_links:
  View on GitHub: https://github.com/ChenPeleg/documentation-pages
